name: Github Actions
run-name: ${{github.actor}} build-pipeline
on: 
    pull_request:
        branches:
            - main

jobs:
    build:
    runs-on: ubuntu-latest
    steps:
        - name: build
          run: |
            echo 'building'

    publish:
        needs: [build]
        runs-on: ubuntu-latest
        environment: production
        steps:
        - name: publish
          run: |
            echo 'publishing'